vikn-books-web/api/v1/employees/urls.py
from django.conf.urls import url,include
from api.v1.employees import views

# app_name='companySettings'

urlpatterns = [
	url(r'^create-employee/$', views.create_employee, name='create_employee'),
    url(r'^employees/$', views.employees, name='employees'),
    url(r'^view/employee/(?P<pk>.*)/$', views.employee, name='employee'),
    url(r'^edit/employee/(?P<pk>.*)/$', views.edit_employee, name='edit_employee'),
    url(r'^delete/employee/(?P<pk>.*)/$', views.delete_employee, name='delete_employee'),

    url(r'^countries/$', views.countries, name='countries'),
]

vikn-books-web/payrolls/urls.py
from django.conf.urls import  url,include
from payrolls import views


app_name = "payrolls"

urlpatterns = [
    url(r'create-designation/',views.create_designation, name="create_designation"),
    url(r'designations/',views.designations, name="designations"),
    url(r'^view/designation/(?P<pk>.*)/$', views.view_designation, name='view_designation'),
    url(r'^edit-designation/(?P<pk>.*)/$', views.edit_designation, name='edit_designation'),
    url(r'^delete-designation/(?P<pk>.*)/$', views.delete_designation, name='delete_designation'),

    url(r'create-department/',views.create_department, name="create_department"),
    url(r'departments/',views.departments, name="departments"),
    url(r'^view/department/(?P<pk>.*)/$', views.view_department, name='view_department'),
    url(r'^edit-department/(?P<pk>.*)/$', views.edit_department, name='edit_department'),
    url(r'^delete-department/(?P<pk>.*)/$', views.delete_department, name='delete_department'),
    
    url(r'create-employee/',views.create_employee, name="create_employee"),
    url(r'employees/',views.employees, name="employees"),
    url(r'^view/employee/(?P<pk>.*)/$', views.view_employee, name='view_employee'),
    url(r'^edit-employee/(?P<pk>.*)/$', views.edit_employee, name='edit_employee'),
    url(r'^delete-employee/(?P<pk>.*)/$', views.delete_employee, name='delete_employee'),
]

vikn-books-web/testproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from api.v1.users import views as users_views
from users import views as general_views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    path(
        "api/v1/auth/",
        include(
            ("api.v1.authentication.urls", "api"), namespace="api_v1_authentication"
        ),
    ),
    url(r"^app/accounts/", include("registration.backends.default.urls")),
    url("", include("pwa.urls")),
    path("api/v1/users/", include("api.v1.users.urls")),
    path("api/v1/brands/", include("api.v1.brands.urls")),
    path("api/v1/units/", include("api.v1.units.urls")),
    path("api/v1/routes/", include("api.v1.routes.urls")),
    path("api/v1/taxCategories/", include("api.v1.taxCategories.urls")),
    path("api/v1/productCategories/", include("api.v1.productCategories.urls")),
    path("api/v1/productGroups/", include("api.v1.productGroups.urls")),
    path("api/v1/warehouses/", include("api.v1.warehouses.urls")),
    path("api/v1/priceCategories/", include("api.v1.priceCategories.urls")),
    path("api/v1/accountGroups/", include("api.v1.accountGroups.urls")),
    path("api/v1/accountLedgers/", include("api.v1.accountLedgers.urls")),
    path("api/v1/branchs/", include("api.v1.branchs.urls")),
    path("api/v1/parties/", include("api.v1.parties.urls")),
    path("api/v1/products/", include("api.v1.products.urls")),
    path("api/v1/priceLists/", include("api.v1.priceLists.urls")),
    path("api/v1/masterTypes/", include("api.v1.masterTypes.urls")),
    path("api/v1/transactionTypes/", include("api.v1.transactionTypes.urls")),
    path("api/v1/colors/", include("api.v1.colors.urls")),
    path("api/v1/companySettings/", include("api.v1.companySettings.urls")),
    path("api/v1/damageStockDetails/", include("api.v1.damageStockDetails.urls")),
    path("api/v1/damageStockMaster/", include("api.v1.damageStockMaster.urls")),
    path("api/v1/designation/", include("api.v1.designation.urls")),
    path("api/v1/department/", include("api.v1.department.urls")),
    path("api/v1/employees/", include("api.v1.employees.urls")),
    path("api/v1/flavours/", include("api.v1.flavours.urls")),
    path("api/v1/journalDetails/", include("api.v1.journalDetails.urls")),
    path("api/v1/journalMaster/", include("api.v1.journalMaster.urls")),
    path("api/v1/kitchen/", include("api.v1.kitchen.urls")),
    path("api/v1/ledgerPosting/", include("api.v1.ledgerPosting.urls")),
    path("api/v1/openingStockDetails/", include("api.v1.openingStockDetails.urls")),
    path("api/v1/openingStockMaster/", include("api.v1.openingStockMaster.urls")),
    path("api/v1/paymentDetails/", include("api.v1.paymentDetails.urls")),
    path("api/v1/paymentMaster/", include("api.v1.paymentMaster.urls")),
    path("api/v1/POSHoldDetails/", include("api.v1.POSHoldDetails.urls")),
    path("api/v1/POSHoldMaster/", include("api.v1.POSHoldMaster.urls")),
    path("api/v1/purchaseDetails/", include("api.v1.purchaseDetails.urls")),
    path("api/v1/purchaseMaster/", include("api.v1.purchaseMaster.urls")),
    path("api/v1/purchaseOrderDetails/", include("api.v1.purchaseOrderDetails.urls")),
    path("api/v1/purchaseOrderMaster/", include("api.v1.purchaseOrderMaster.urls")),
    path("api/v1/purchaseReturnDetails/", include("api.v1.purchaseReturnDetails.urls")),
    path("api/v1/purchaseReturnMaster/", include("api.v1.purchaseReturnMaster.urls")),
    path("api/v1/receiptDetails/", include("api.v1.receiptDetails.urls")),
    path("api/v1/receiptMaster/", include("api.v1.receiptMaster.urls")),
    path("api/v1/salesDetails/", include("api.v1.salesDetails.urls")),
    path("api/v1/salesMaster/", include("api.v1.salesMaster.urls")),
    path("api/v1/salesOrderDetails/", include("api.v1.salesOrderDetails.urls")),
    path("api/v1/salesOrderMaster/", include("api.v1.salesOrderMaster.urls")),
    path("api/v1/salesReturnDetails/", include("api.v1.salesReturnDetails.urls")),
    path("api/v1/salesReturnMaster/", include("api.v1.salesReturnMaster.urls")),
    path("api/v1/settings/", include("api.v1.settings.urls")),
    path(
        "api/v1/stockAdjustmentDetails/", include("api.v1.stockAdjustmentDetails.urls")
    ),
    path("api/v1/stockAdjustmentMaster/", include("api.v1.stockAdjustmentMaster.urls")),
    path("api/v1/stockReceiptDetails/", include("api.v1.stockReceiptDetails.urls")),
    path("api/v1/stockReceiptMasterID/", include("api.v1.stockReceiptMasterID.urls")),
    path("api/v1/stockTransferDetails/", include("api.v1.stockTransferDetails.urls")),
    path("api/v1/stockTransferMasterID/", include("api.v1.stockTransferMasterID.urls")),
    path("api/v1/stockPostings/", include("api.v1.stockPostings.urls")),
    path("api/v1/stockRates/", include("api.v1.stockRates.urls")),
    path("api/v1/banks/", include("api.v1.banks.urls")),
    path("api/v1/financialYear/", include("api.v1.financialYear.urls")),
    path("api/v1/damageStock/", include("api.v1.damageStock.urls")),
    path("api/v1/openingStock/", include("api.v1.openingStock.urls")),
    path("api/v1/payments/", include("api.v1.payments.urls")),
    path("api/v1/posholds/", include("api.v1.posholds.urls")),
    path("api/v1/purchases/", include("api.v1.purchases.urls")),
    path("api/v1/receipts/", include("api.v1.receipts.urls")),
    path("api/v1/purchaseOrders/", include("api.v1.purchaseOrders.urls")),
    path("api/v1/purchaseReturns/", include("api.v1.purchaseReturns.urls")),
    path("api/v1/sales/", include("api.v1.sales.urls")),
    path("api/v1/salesOrders/", include("api.v1.salesOrders.urls")),
    path("api/v1/salesReturns/", include("api.v1.salesReturns.urls")),
    path("api/v1/stockAdjustments/", include("api.v1.stockAdjustments.urls")),
    path("api/v1/stockReceipts/", include("api.v1.stockReceipts.urls")),
    path("api/v1/stockTransfers/", include("api.v1.stockTransfers.urls")),
    path("api/v1/journals/", include("api.v1.journals.urls")),
    path("api/v1/countries/", include("api.v1.countries.urls")),
    path("api/v1/states/", include("api.v1.states.urls")),
    path("api/v1/businessTypes/", include("api.v1.businessTypes.urls")),
    path("api/v1/organizations/", include("api.v1.organizations.urls")),
    path("api/v1/userTable/", include("api.v1.userTable.urls")),
    path(
        "api/v1/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    # version2 urls
    path("api/v2/users/", include("api.v2.users.urls")),
    path("api/v2/brands/", include("api.v2.brands.urls")),
    path("api/v2/units/", include("api.v2.units.urls")),
    path("api/v2/routes/", include("api.v2.routes.urls")),
    path("api/v2/taxCategories/", include("api.v2.taxCategories.urls")),
    path("api/v2/productCategories/", include("api.v2.productCategories.urls")),
    path("api/v2/productGroups/", include("api.v2.productGroups.urls")),
    path("api/v2/warehouses/", include("api.v2.warehouses.urls")),
    path("api/v2/priceCategories/", include("api.v2.priceCategories.urls")),
    path("api/v2/accountGroups/", include("api.v2.accountGroups.urls")),
    path("api/v2/accountLedgers/", include("api.v2.accountLedgers.urls")),
    path("api/v2/branchs/", include("api.v2.branchs.urls")),
    path("api/v2/parties/", include("api.v2.parties.urls")),
    path("api/v2/products/", include("api.v2.products.urls")),
    path("api/v2/priceLists/", include("api.v2.priceLists.urls")),
    path("api/v2/masterTypes/", include("api.v2.masterTypes.urls")),
    path("api/v2/transactionTypes/", include("api.v2.transactionTypes.urls")),
    path("api/v2/colors/", include("api.v2.colors.urls")),
    path("api/v2/companySettings/", include("api.v2.companySettings.urls")),
    path("api/v2/damageStockDetails/", include("api.v2.damageStockDetails.urls")),
    path("api/v2/damageStockMaster/", include("api.v2.damageStockMaster.urls")),
    path("api/v2/designation/", include("api.v2.designation.urls")),
    path("api/v2/department/", include("api.v2.department.urls")),
    path("api/v2/employees/", include("api.v2.employees.urls")),
    path("api/v2/flavours/", include("api.v2.flavours.urls")),
    path("api/v2/journalDetails/", include("api.v2.journalDetails.urls")),
    path("api/v2/journalMaster/", include("api.v2.journalMaster.urls")),
    path("api/v2/kitchen/", include("api.v2.kitchen.urls")),
    path("api/v2/ledgerPosting/", include("api.v2.ledgerPosting.urls")),
    path("api/v2/openingStockDetails/", include("api.v2.openingStockDetails.urls")),
    path("api/v2/openingStockMaster/", include("api.v2.openingStockMaster.urls")),
    path("api/v2/paymentDetails/", include("api.v2.paymentDetails.urls")),
    path("api/v2/paymentMaster/", include("api.v2.paymentMaster.urls")),
    path("api/v2/POSHoldDetails/", include("api.v2.POSHoldDetails.urls")),
    path("api/v2/POSHoldMaster/", include("api.v2.POSHoldMaster.urls")),
    path("api/v2/purchaseDetails/", include("api.v2.purchaseDetails.urls")),
    path("api/v2/purchaseMaster/", include("api.v2.purchaseMaster.urls")),
    path("api/v2/purchaseOrderDetails/", include("api.v2.purchaseOrderDetails.urls")),
    path("api/v2/purchaseOrderMaster/", include("api.v2.purchaseOrderMaster.urls")),
    path("api/v2/purchaseReturnDetails/", include("api.v2.purchaseReturnDetails.urls")),
    path("api/v2/purchaseReturnMaster/", include("api.v2.purchaseReturnMaster.urls")),
    path("api/v2/receiptDetails/", include("api.v2.receiptDetails.urls")),
    path("api/v2/receiptMaster/", include("api.v2.receiptMaster.urls")),
    path("api/v2/salesDetails/", include("api.v2.salesDetails.urls")),
    path("api/v2/salesMaster/", include("api.v2.salesMaster.urls")),
    path("api/v2/salesOrderDetails/", include("api.v2.salesOrderDetails.urls")),

vikn-books-web/web/urls.py
from django.conf.urls import  url,include
from web import views


app_name = "web"

urlpatterns = [

    url(r'^$',views.home, name="home"),
    # url(r'create-brand/',views.create_brand, name="create_brand"),
    # url(r'brands/',views.brands, name="brands"),
    # url(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    # url(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    # url(r'account-groups/',views.account_groups, name="account_groups"),

    # url(r'create-branch/',views.create_branch, name="create_branch"),
    # url(r'branchs/',views.branchs, name="branchs"),
    # url(r'^edit-branch/(?P<pk>.*)/$', views.edit_branch, name='edit_branch'),
    # url(r'^delete-branch/(?P<pk>.*)/$', views.delete_branch, name='delete_branch'),

    # url(r'create-accountLedger/',views.create_accountLedger, name="create_accountLedger"),
    # url(r'accountLedgers/',views.accountLedgers, name="accountLedgers"),
    # url(r'^edit-accountLedger/(?P<pk>.*)/$', views.edit_accountLedger, name='edit_accountLedger'),
    # url(r'^delete-accountLedger/(?P<pk>.*)/$', views.delete_accountLedger, name='delete_accountLedger'),

    # url(r'create-bank/',views.create_bank, name="create_bank"),
    # url(r'banks/',views.banks, name="banks"),
    # url(r'^edit-bank/(?P<pk>.*)/$', views.edit_bank, name='edit_bank'),

]

vikn-books-web/payrolls/models.py
from django.db import models

# Create your models here.

vikn-books-web/templates/payrolls/masters/department.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">{{title}}</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}} - {{instance.DesignationName}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card-box">

                        <div class="row mb-2">
                                <div class="col-md-12">
                                    <div class="text-md-right">
                                        <a href="{% url 'payrolls:edit_department' pk=instance.pk %}" class="btn btn-info waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-pencil mr-1"></i>Edit {{title}}</a>

                                        <a data-id="{{instance.pk}}" href="{% url 'payrolls:delete_department' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-info waves-effect waves-light mb-2 mr-2 redirect"><i class="mdi mdi-delete mr-1"></i>Delete {{title}}</a>

                               

                                    </div>
                                </div><!-- end col-->
                            </div>

                        <div class="table-responsive mt-4">
                            <table class="table table-bordered table-centered mb-0">
                                <tbody>
                                    <tr>
                                        <td>DepartmentID</td>
                                        <td>{{instance.DepartmentID}}</td>
                                    </tr>
                                    <tr>
                                        <td>BranchID</td>
                                        <td>{{instance.BranchID}}</td>
                                    </tr>
                                    <tr>
                                        <td>DepartmentName</td>
                                        <td>{{instance.DepartmentName}}</td>
                                    </tr>
                                    <tr>
                                        <td>Notes</td>
                                        <td>{{instance.Notes}}</td>
                                    </tr>
                                    <tr>
                                        <td>CreatedUserID</td>
                                        <td>{{instance.CreatedUserID}}</td>
                                    </tr>
                                    <tr>
                                        <td>CreatedDate</td>
                                        <td>{{instance.CreatedDate}}</td>
                                    </tr>
                                    <tr>
                                        <td>UpdatedDate</td>
                                        <td>{{instance.UpdatedDate}}</td>
                                    </tr>
                                    <tr>
                                        <td>Action</td>
                                        <td>{{instance.Action}}</td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div>

                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}

vikn-books-web/templates/payrolls/masters/departments.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">{{title}}</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <form class="search-bar form-inline">
                                        <div class="position-relative">
                                            <input type="text" name="q" class="form-control" placeholder="Search...">
                                            <span class="mdi mdi-magnify"></span>
                                        </div>
                                    </form>                          
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-right">
                                        <a href="{% url 'payrolls:create_department' %}" class="btn btn-info waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-plus mr-1"></i>Create {{title}}</a>
                                    </div>
                                </div><!-- end col-->
                            </div>
                        
                        {% if instances %}
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-borderless table-hover mb-0">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>#</th>
                                            <th>DepartmentID</th>
                                            <th>BranchID</th>
                                            <th>DepartmentName</th>
                                            <th>Notes</th>
                                            <th style="width: 82px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 21 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="table-user">
                                                <a href="javascript:void(0);" class="text-body font-weight-semibold">{{ instance.id }}</a>
                                            </td>
                                            <td>
                                                {{ instance.DepartmentID }}
                                            </td>
                                            <td>
                                                {{ instance.BranchID }}
                                            </td>
                                            <td>
                                                {{ instance.DepartmentName }}
                                            </td>
                                            <td>
                                                 {{ instance.Notes }}
                                            </td>
        
                                            <td>
                                                <a href="{% url 'payrolls:view_department' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                                <a href="{% url 'payrolls:edit_department' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                                <a data-id="{{instance.pk}}" href="{% url 'payrolls:delete_department' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-icon action-button remove"> <i class="mdi mdi-delete"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <!--pagination -->
                            {% get_pages %}
                             <div class="pagination pagination-rounded justify-content-end my-2">
                                {% show_pages %}
                            </div>
                            <!--pagination-->
                            {% else %}
                            {% include 'includes/not_found.html' %}
                            {% endif %}

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}

vikn-books-web/templates/payrolls/masters/designations.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">{{title}}</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <form class="search-bar form-inline">
                                        <div class="position-relative">
                                            <input type="text" name="q" class="form-control" placeholder="Search...">
                                            <span class="mdi mdi-magnify"></span>
                                        </div>
                                    </form>                          
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-right">
                                        <a href="{% url 'payrolls:create_designation' %}" class="btn btn-info waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-plus mr-1"></i>Create {{title}}</a>
                                    </div>
                                </div><!-- end col-->
                            </div>
                        
                        {% if instances %}
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-borderless table-hover mb-0">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>#</th>
                                            <th>DesignationID</th>
                                            <th>BranchID</th>
                                            <th>Designation Name</th>
                                            <th>Notes</th>
                                            <th>CreatedDate</th>
                                            <th>Action</th>
                                            <th style="width: 82px;">£</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 21 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="table-user">
                                                <a href="javascript:void(0);" class="text-body font-weight-semibold">{{ instance.id }}</a>
                                            </td>
                                            <td>
                                                {{ instance.DesignationID }}
                                            </td>
                                            <td>
                                                {{ instance.BranchID }}
                                            </td>
                                            <td>
                                                {{ instance.DesignationName }}
                                            </td>
                                            <td>
                                                {{ instance.Notes }}
                                            </td>
                                            <td>
                                                {{ instance.CreatedDate }}
                                            </td>
                                            <td>
                                                {{ instance.Action }}
                                            </td>
        
                                            <td>
                                                <a href="{% url 'payrolls:view_designation' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                                <a href="{% url 'payrolls:edit_designation' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                                <a data-id="{{instance.pk}}" href="{% url 'payrolls:delete_designation' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-icon action-button remove"> <i class="mdi mdi-delete"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <!--pagination -->
                            {% get_pages %}
                             <div class="pagination pagination-rounded justify-content-end my-2">
                                {% show_pages %}
                            </div>
                            <!--pagination-->
                            {% else %}
                            {% include 'includes/not_found.html' %}
                            {% endif %}

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}