vikn-books-web/api/v1/users/urls.py
from django.conf.urls import url, include
from django.urls import path, include
from api.v1.users import views


urlpatterns = [
    url(r'^create-user/$', views.create_user, name='create_user'),
    url(r'^users/$', views.users, name='users'),
    url(r'^customers/$', views.customers, name='customers'),
    url(r'^user-types/$', views.user_types, name='user_types'),
    url(r'^view/user/(?P<pk>.*)/$', views.user, name='user'),
    url(r'^edit/user/(?P<pk>.*)/$', views.edit_user, name='edit_user'),
    url(r'^delete/user/(?P<pk>.*)/$', views.delete_user, name='delete_user'),

    url(r'^check-user/$', views.check_user, name='check_user'),
    url(r'^user-login/$', views.user_login, name='user_login'),
    url(r'^user-signup/$', views.user_signup, name='user_signup'),
    url(r'^companies/$', views.companies, name='companies'),
    url(r'^logout-view/$', views.logout_view, name='logout_view'),
    url(r'^create-company/$', views.create_company, name='create_company'),
    url(r'^user-accounts/$', views.user_accounts, name='user_accounts'),
    url(r'^update-user/$', views.update_user, name='update_user'),
    url(r'^user-view/(?P<pk>.*)/$', views.user_view, name='user_view'),

    url(r'^create-user-type/$', views.create_user_type, name='create_user_type'),
    url(r'^userTypes/$', views.userTypes, name='userTypes'),
    url(r'^view/userType/(?P<pk>.*)/$', views.userType, name='userType'),
    url(r'^edit/userType/(?P<pk>.*)/$', views.edit_userType, name='edit_userType'),
    url(r'^delete/userType/(?P<pk>.*)/$',views.delete_userType, name='delete_userType'),

    url(r'^create-general-settings/$', views.create_general_settings,name='create_general_settings'),
    url(r'^general-settings-list/$', views.general_settings_list,name='general_settings_list'),

    url(r'^get-default-values/$', views.get_defaults, name='get_defaults'),

    url(r'^activity-logs/$', views.activity_logs, name='activity_logs'),
    url(r'^activity-log/(?P<pk>.*)/$', views.activity_log, name='activity_log'),
    

]

vikn-books-web/testproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from api.v1.users import views as users_views
from users import views as general_views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    path(
        "api/v1/auth/",
        include(
            ("api.v1.authentication.urls", "api"), namespace="api_v1_authentication"
        ),
    ),
    url(r"^app/accounts/", include("registration.backends.default.urls")),
    url("", include("pwa.urls")),
    path("api/v1/users/", include("api.v1.users.urls")),
    path("api/v1/brands/", include("api.v1.brands.urls")),
    path("api/v1/units/", include("api.v1.units.urls")),
    path("api/v1/routes/", include("api.v1.routes.urls")),
    path("api/v1/taxCategories/", include("api.v1.taxCategories.urls")),
    path("api/v1/productCategories/", include("api.v1.productCategories.urls")),
    path("api/v1/productGroups/", include("api.v1.productGroups.urls")),
    path("api/v1/warehouses/", include("api.v1.warehouses.urls")),
    path("api/v1/priceCategories/", include("api.v1.priceCategories.urls")),
    path("api/v1/accountGroups/", include("api.v1.accountGroups.urls")),
    path("api/v1/accountLedgers/", include("api.v1.accountLedgers.urls")),
    path("api/v1/branchs/", include("api.v1.branchs.urls")),
    path("api/v1/parties/", include("api.v1.parties.urls")),
    path("api/v1/products/", include("api.v1.products.urls")),
    path("api/v1/priceLists/", include("api.v1.priceLists.urls")),
    path("api/v1/masterTypes/", include("api.v1.masterTypes.urls")),
    path("api/v1/transactionTypes/", include("api.v1.transactionTypes.urls")),
    path("api/v1/colors/", include("api.v1.colors.urls")),
    path("api/v1/companySettings/", include("api.v1.companySettings.urls")),
    path("api/v1/damageStockDetails/", include("api.v1.damageStockDetails.urls")),
    path("api/v1/damageStockMaster/", include("api.v1.damageStockMaster.urls")),
    path("api/v1/designation/", include("api.v1.designation.urls")),
    path("api/v1/department/", include("api.v1.department.urls")),
    path("api/v1/employees/", include("api.v1.employees.urls")),
    path("api/v1/flavours/", include("api.v1.flavours.urls")),
    path("api/v1/journalDetails/", include("api.v1.journalDetails.urls")),
    path("api/v1/journalMaster/", include("api.v1.journalMaster.urls")),
    path("api/v1/kitchen/", include("api.v1.kitchen.urls")),
    path("api/v1/ledgerPosting/", include("api.v1.ledgerPosting.urls")),
    path("api/v1/openingStockDetails/", include("api.v1.openingStockDetails.urls")),
    path("api/v1/openingStockMaster/", include("api.v1.openingStockMaster.urls")),
    path("api/v1/paymentDetails/", include("api.v1.paymentDetails.urls")),
    path("api/v1/paymentMaster/", include("api.v1.paymentMaster.urls")),
    path("api/v1/POSHoldDetails/", include("api.v1.POSHoldDetails.urls")),
    path("api/v1/POSHoldMaster/", include("api.v1.POSHoldMaster.urls")),
    path("api/v1/purchaseDetails/", include("api.v1.purchaseDetails.urls")),
    path("api/v1/purchaseMaster/", include("api.v1.purchaseMaster.urls")),
    path("api/v1/purchaseOrderDetails/", include("api.v1.purchaseOrderDetails.urls")),
    path("api/v1/purchaseOrderMaster/", include("api.v1.purchaseOrderMaster.urls")),
    path("api/v1/purchaseReturnDetails/", include("api.v1.purchaseReturnDetails.urls")),
    path("api/v1/purchaseReturnMaster/", include("api.v1.purchaseReturnMaster.urls")),
    path("api/v1/receiptDetails/", include("api.v1.receiptDetails.urls")),
    path("api/v1/receiptMaster/", include("api.v1.receiptMaster.urls")),
    path("api/v1/salesDetails/", include("api.v1.salesDetails.urls")),
    path("api/v1/salesMaster/", include("api.v1.salesMaster.urls")),
    path("api/v1/salesOrderDetails/", include("api.v1.salesOrderDetails.urls")),
    path("api/v1/salesOrderMaster/", include("api.v1.salesOrderMaster.urls")),
    path("api/v1/salesReturnDetails/", include("api.v1.salesReturnDetails.urls")),
    path("api/v1/salesReturnMaster/", include("api.v1.salesReturnMaster.urls")),
    path("api/v1/settings/", include("api.v1.settings.urls")),
    path(
        "api/v1/stockAdjustmentDetails/", include("api.v1.stockAdjustmentDetails.urls")
    ),
    path("api/v1/stockAdjustmentMaster/", include("api.v1.stockAdjustmentMaster.urls")),
    path("api/v1/stockReceiptDetails/", include("api.v1.stockReceiptDetails.urls")),
    path("api/v1/stockReceiptMasterID/", include("api.v1.stockReceiptMasterID.urls")),
    path("api/v1/stockTransferDetails/", include("api.v1.stockTransferDetails.urls")),
    path("api/v1/stockTransferMasterID/", include("api.v1.stockTransferMasterID.urls")),
    path("api/v1/stockPostings/", include("api.v1.stockPostings.urls")),
    path("api/v1/stockRates/", include("api.v1.stockRates.urls")),
    path("api/v1/banks/", include("api.v1.banks.urls")),
    path("api/v1/financialYear/", include("api.v1.financialYear.urls")),
    path("api/v1/damageStock/", include("api.v1.damageStock.urls")),
    path("api/v1/openingStock/", include("api.v1.openingStock.urls")),
    path("api/v1/payments/", include("api.v1.payments.urls")),
    path("api/v1/posholds/", include("api.v1.posholds.urls")),
    path("api/v1/purchases/", include("api.v1.purchases.urls")),
    path("api/v1/receipts/", include("api.v1.receipts.urls")),
    path("api/v1/purchaseOrders/", include("api.v1.purchaseOrders.urls")),
    path("api/v1/purchaseReturns/", include("api.v1.purchaseReturns.urls")),
    path("api/v1/sales/", include("api.v1.sales.urls")),
    path("api/v1/salesOrders/", include("api.v1.salesOrders.urls")),
    path("api/v1/salesReturns/", include("api.v1.salesReturns.urls")),
    path("api/v1/stockAdjustments/", include("api.v1.stockAdjustments.urls")),
    path("api/v1/stockReceipts/", include("api.v1.stockReceipts.urls")),
    path("api/v1/stockTransfers/", include("api.v1.stockTransfers.urls")),
    path("api/v1/journals/", include("api.v1.journals.urls")),
    path("api/v1/countries/", include("api.v1.countries.urls")),
    path("api/v1/states/", include("api.v1.states.urls")),
    path("api/v1/businessTypes/", include("api.v1.businessTypes.urls")),
    path("api/v1/organizations/", include("api.v1.organizations.urls")),
    path("api/v1/userTable/", include("api.v1.userTable.urls")),
    path(
        "api/v1/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    # version2 urls
    path("api/v2/users/", include("api.v2.users.urls")),
    path("api/v2/brands/", include("api.v2.brands.urls")),
    path("api/v2/units/", include("api.v2.units.urls")),
    path("api/v2/routes/", include("api.v2.routes.urls")),
    path("api/v2/taxCategories/", include("api.v2.taxCategories.urls")),
    path("api/v2/productCategories/", include("api.v2.productCategories.urls")),
    path("api/v2/productGroups/", include("api.v2.productGroups.urls")),
    path("api/v2/warehouses/", include("api.v2.warehouses.urls")),
    path("api/v2/priceCategories/", include("api.v2.priceCategories.urls")),
    path("api/v2/accountGroups/", include("api.v2.accountGroups.urls")),
    path("api/v2/accountLedgers/", include("api.v2.accountLedgers.urls")),
    path("api/v2/branchs/", include("api.v2.branchs.urls")),
    path("api/v2/parties/", include("api.v2.parties.urls")),
    path("api/v2/products/", include("api.v2.products.urls")),
    path("api/v2/priceLists/", include("api.v2.priceLists.urls")),
    path("api/v2/masterTypes/", include("api.v2.masterTypes.urls")),
    path("api/v2/transactionTypes/", include("api.v2.transactionTypes.urls")),
    path("api/v2/colors/", include("api.v2.colors.urls")),
    path("api/v2/companySettings/", include("api.v2.companySettings.urls")),
    path("api/v2/damageStockDetails/", include("api.v2.damageStockDetails.urls")),
    path("api/v2/damageStockMaster/", include("api.v2.damageStockMaster.urls")),
    path("api/v2/designation/", include("api.v2.designation.urls")),
    path("api/v2/department/", include("api.v2.department.urls")),
    path("api/v2/employees/", include("api.v2.employees.urls")),
    path("api/v2/flavours/", include("api.v2.flavours.urls")),
    path("api/v2/journalDetails/", include("api.v2.journalDetails.urls")),
    path("api/v2/journalMaster/", include("api.v2.journalMaster.urls")),
    path("api/v2/kitchen/", include("api.v2.kitchen.urls")),
    path("api/v2/ledgerPosting/", include("api.v2.ledgerPosting.urls")),
    path("api/v2/openingStockDetails/", include("api.v2.openingStockDetails.urls")),
    path("api/v2/openingStockMaster/", include("api.v2.openingStockMaster.urls")),
    path("api/v2/paymentDetails/", include("api.v2.paymentDetails.urls")),
    path("api/v2/paymentMaster/", include("api.v2.paymentMaster.urls")),
    path("api/v2/POSHoldDetails/", include("api.v2.POSHoldDetails.urls")),
    path("api/v2/POSHoldMaster/", include("api.v2.POSHoldMaster.urls")),
    path("api/v2/purchaseDetails/", include("api.v2.purchaseDetails.urls")),
    path("api/v2/purchaseMaster/", include("api.v2.purchaseMaster.urls")),
    path("api/v2/purchaseOrderDetails/", include("api.v2.purchaseOrderDetails.urls")),
    path("api/v2/purchaseOrderMaster/", include("api.v2.purchaseOrderMaster.urls")),
    path("api/v2/purchaseReturnDetails/", include("api.v2.purchaseReturnDetails.urls")),
    path("api/v2/purchaseReturnMaster/", include("api.v2.purchaseReturnMaster.urls")),
    path("api/v2/receiptDetails/", include("api.v2.receiptDetails.urls")),
    path("api/v2/receiptMaster/", include("api.v2.receiptMaster.urls")),
    path("api/v2/salesDetails/", include("api.v2.salesDetails.urls")),
    path("api/v2/salesMaster/", include("api.v2.salesMaster.urls")),
    path("api/v2/salesOrderDetails/", include("api.v2.salesOrderDetails.urls")),

vikn-books-web/users/urls.py
from django.conf.urls import  url,include
from django.urls import path
# from main import views as general_views
from users import views
app_name = 'users'

urlpatterns = [
    # url(r'^$', views.dashboard, name='dashboard'),
    # url(r'^$', views.companies, name='companies'),
    url(r'^create-db-user/(?P<pk>.*)/$',views.create_db_user,name="create_db_user"), 
    url(r'^login-db-user/$',views.login_db_user,name="login_db_user"),
    url(r'^create-user',views.create_user,name="create_user"),
    # url(r'^create-database/(?P<pk>.*)/$',views.create_database,name="create_database"),
    # path("create-user", views.create_user, name="Create User"),
]

vikn-books-web/web/urls.py
from django.conf.urls import  url,include
from web import views


app_name = "web"

urlpatterns = [

    url(r'^$',views.home, name="home"),
    # url(r'create-brand/',views.create_brand, name="create_brand"),
    # url(r'brands/',views.brands, name="brands"),
    # url(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    # url(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    # url(r'account-groups/',views.account_groups, name="account_groups"),

    # url(r'create-branch/',views.create_branch, name="create_branch"),
    # url(r'branchs/',views.branchs, name="branchs"),
    # url(r'^edit-branch/(?P<pk>.*)/$', views.edit_branch, name='edit_branch'),
    # url(r'^delete-branch/(?P<pk>.*)/$', views.delete_branch, name='delete_branch'),

    # url(r'create-accountLedger/',views.create_accountLedger, name="create_accountLedger"),
    # url(r'accountLedgers/',views.accountLedgers, name="accountLedgers"),
    # url(r'^edit-accountLedger/(?P<pk>.*)/$', views.edit_accountLedger, name='edit_accountLedger'),
    # url(r'^delete-accountLedger/(?P<pk>.*)/$', views.delete_accountLedger, name='delete_accountLedger'),

    # url(r'create-bank/',views.create_bank, name="create_bank"),
    # url(r'banks/',views.banks, name="banks"),
    # url(r'^edit-bank/(?P<pk>.*)/$', views.edit_bank, name='edit_bank'),

]

vikn-books-web/templates/companies/companies.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}

<div class="content-page" {% if is_superuser %} style="margin-left: 0;" {% endif %}>
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">Sellers</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <form class="search-bar form-inline">
                                        <div class="position-relative">
                                            <input type="text" name="q" class="form-control" placeholder="Search...">
                                            <span class="mdi mdi-magnify"></span>
                                        </div>
                                    </form>                          
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-right">
                                        <a href="{% url 'users:create_company' %}" class="btn btn-danger waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-basket mr-1"></i>Create Compnay</a>
                                        <button type="button" class="btn btn-success waves-effect waves-light mb-2 mr-1"><i class="mdi mdi-cog"></i></button>
                                    </div>
                                </div><!-- end col-->
                            </div>
                            {% if instances %}
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-borderless table-hover mb-0">
                                    <thead class="thead-light">
                                        <tr style="text-align: center;">
                                            <th>Company Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 21 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td style="text-align: center;">
                                                <a href="{% url 'users:create_db_user' pk=instance.id %}" class="text-body font-weight-semibold">{{instance.CompanyName.title}}</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <!--pagination -->
                            {% get_pages %}
                             <div class="pagination pagination-rounded justify-content-end my-2">
                                {% show_pages %}
                            </div>
                            <!--pagination-->
                            {% else %}
                            {% include 'includes/not_found.html' %}
                            {% endif %}

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
            
        </div> <!-- container -->

    </div> <!-- content -->

{% endblock %}

vikn-books-web/templates/companies/create_db_user.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page" {% if is_superuser %} style="margin-left: 0;" {% endif %}>
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Projects</a></li>
                                <li class="breadcrumb-item active">Create Project</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row">
                                <div class="col-xl-6">
                                    <form enctype="multipart/form-data" method="post" action="" class="ajax reset redirect ahs-input" novalidate>
                                        {% csrf_token %}
                                        {% for form_data in form %}
                                        <div class="form-group mb-3">
                                            {{ form_data.label }}
                                            {{ form_data }}
                                        </div>
                                        {% endfor %}
                                        <div class="form-group mb-3">
                                            <label for="">User Type</label>
                                            <select class="custom-select" name="UserTypeID">
                                                {% for user_type in user_types %}
                                                <option value="{{ user_type.ID }}">{{ user_type.UserTypeName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group mb-3">
                                            <label for="">Cash Account</label>
                                            <select class="custom-select" name="Cash_Account">
                                                {% for cash_account in cash_accounts %}
                                                <option value="{{ cash_account.LedgerID }}">{{ cash_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Bank Account</label>
                                            <select class="custom-select" name="Bank_Account">
                                                {% for bank_account in bank_accounts %}
                                                <option value="{{ bank_account.LedgerID }}">{{ bank_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Warehouse</label>
                                            <select class="custom-select" name="Warehouse">
                                                {% for warehouse in warehouses %}
                                                <option value="{{ warehouse.WarehouseID }}">{{ warehouse.WarehouseName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Sales Account</label>
                                            <select class="custom-select" name="Sales_Account">
                                                {% for sales_account in sales_accounts %}
                                                <option value="{{ sales_account.LedgerID }}">{{ sales_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Sales Return Account</label>
                                            <select class="custom-select" name="Sales_Return_Account">
                                                {% for sales_account in sales_accounts %}
                                                <option value="{{ sales_account.LedgerID }}">{{ sales_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Purchase Account</label>
                                            <select class="custom-select" name="Purchase_Account">
                                                {% for purchase_account in purchase_accounts %}
                                                <option value="{{ purchase_account.LedgerID }}">{{ purchase_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Purchase Return Account</label>
                                            <select class="custom-select" name="Purchase_Return_Account">
                                                {% for purchase_account in purchase_accounts %}
                                                <option value="{{ purchase_account.LedgerID }}">{{ purchase_account.LedgerName }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Sales GST Type</label>
                                            <select class="custom-select" name="Sales_GST_Type">
                                                {% for sales_gst_type in sales_gst_types %}
                                                <option value="{{ sales_gst_type.TransactionTypesID }}">{{ sales_gst_type.Name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">Purchase GST Type</label>
                                            <select class="custom-select" name="Purchase_GST_Type">
                                                {% for purchase_gst_type in purchase_gst_types %}
                                                <option value="{{ purchase_gst_type.TransactionTypesID }}">{{ purchase_gst_type.Name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="">VAT Type</label>
                                            <select class="custom-select" name="VAT_Type">
                                                {% for vat_type in vat_types %}
                                                <option value="{{ vat_type.TransactionTypesID }}">{{ vat_type.Name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label>Expiry Date</label>
                                            <input type="date" class="required form-control dateinput" type="" value="" name="ExpiryDate" placeholder="Expiry Date">
                                        </div>


                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </form>

                                </div> <!-- end col-->
                            </div>
                            <!-- end row -->

                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}

vikn-books-web/templates/companies/login_db_user.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page" {% if is_superuser %} style="margin-left: 0;" {% endif %}>
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Projects</a></li>
                                <li class="breadcrumb-item active">Create Project</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row">
                                <div class="col-xl-6">
                                    <form enctype="multipart/form-data" method="post" action="" class="ajax reset redirect ahs-input" novalidate>
                                        {% csrf_token %}
                                        {% for form_data in form %}
                                        <div class="form-group mb-3">
                                            {{ form_data.label }}
                                            {{ form_data }}
                                        </div>
                                        {% endfor %}
                                        
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </form>

                                </div> <!-- end col-->
                            </div>
                            <!-- end row -->

                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col-->
            </div>
            <!-- end row-->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}