vikn-books-web/accounts/urls.py
from django.conf.urls import  url,include
from accounts import views


app_name = "accounts"

urlpatterns = [
    # Masters
    url(r'create-accountGroup/',views.create_accountGroup, name="create_accountGroup"),
    url(r'account-groups/',views.account_groups, name="account_groups"),
    url(r'^view-accountGroup/(?P<pk>.*)/$', views.view_accountGroup, name='view_accountGroup'),
    url(r'^edit-accountGroup/(?P<pk>.*)/$', views.edit_accountGroup, name='edit_accountGroup'),
    url(r'^delete-accountGroup/(?P<pk>.*)/$', views.delete_accountGroup, name='delete_accountGroup'),

    url(r'create-accountLedger/',views.create_accountLedger, name="create_accountLedger"),
    url(r'accountLedgers/',views.accountLedgers, name="accountLedgers"),
    url(r'^view-accountLedger/(?P<pk>.*)/$', views.view_accountLedger, name='view_accountLedger'),
    url(r'^edit-accountLedger/(?P<pk>.*)/$', views.edit_accountLedger, name='edit_accountLedger'),
    url(r'^delete-accountLedger/(?P<pk>.*)/$', views.delete_accountLedger, name='delete_accountLedger'),

    url(r'create-branch/',views.create_branch, name="create_branch"),
    url(r'branchs/',views.branchs, name="branchs"),
    url(r'^view-branch/(?P<pk>.*)/$', views.view_branch, name='view_branch'),
    url(r'^edit-branch/(?P<pk>.*)/$', views.edit_branch, name='edit_branch'),
    url(r'^delete-branch/(?P<pk>.*)/$', views.delete_branch, name='delete_branch'),

    url(r'create-bank/',views.create_bank, name="create_bank"),
    url(r'banks/',views.banks, name="banks"),
    url(r'^edit-bank/(?P<pk>.*)/$', views.edit_bank, name='edit_bank'),
    url(r'^view-bank/(?P<pk>.*)/$', views.view_bank, name='view_bank'),
    url(r'^delete-bank/(?P<pk>.*)/$', views.delete_bank, name='delete_bank'),

    url(r'create-customer/',views.create_customer, name="create_customer"),
    url(r'customers/',views.customers, name="customers"),
    url(r'^view-customer/(?P<pk>.*)/$', views.view_customer, name='view_customer'),
    url(r'^edit-customer/(?P<pk>.*)/$', views.edit_customer, name='edit_customer'),
    url(r'^delete-customer/(?P<pk>.*)/$', views.delete_customer, name='delete_customer'),


    url(r'create-supplier/',views.create_supplier, name="create_supplier"),
    url(r'suppliers/',views.suppliers, name="suppliers"),
    url(r'^view-supplier/(?P<pk>.*)/$', views.view_supplier, name='view_supplier'),
    url(r'^edit-supplier/(?P<pk>.*)/$', views.edit_supplier, name='edit_supplier'),
    url(r'^delete-supplier/(?P<pk>.*)/$', views.delete_supplier, name='delete_supplier'),

    url(r'create-transactionType/',views.create_transactionType, name="create_transactionType"),
    url(r'transactionTypes/',views.transactionTypes, name="transactionTypes"),
    url(r'^view-transactionType/(?P<pk>.*)/$', views.view_transactionType, name='view_transactionType'),
    url(r'^edit-transactionType/(?P<pk>.*)/$', views.edit_transactionType, name='edit_transactionType'),
    url(r'^delete-transactionType/(?P<pk>.*)/$', views.delete_transactionType, name='delete_transactionType'),
    # Reports
    url(r'^trialBalance-webView/$', views.trialBalance_webView, name='trialBalance_webView'),
    url(r'^ledgerReport-webView/$', views.ledgerReport_webView, name='ledgerReport_webView'),
    url(r'^ledgerReport-ledgerWise/$', views.ledgerReport_LedgerWise, name='ledgerReport_LedgerWise'),
    url(r'^profit-and-loss-webview/$', views.profitAndLoss_webView, name='profitAndLoss_webView'),

    url(r'create-cash-payment/',views.create_cash_payment, name="create_cash_payment"),
    url(r'cash-payments/',views.cash_payments, name="cash_payments"),
    url(r'^cash-payment/(?P<pk>.*)/$', views.cash_payment, name='cash_payment'),
    url(r'^edit-cash-payment/(?P<pk>.*)/$', views.edit_cash_payment, name='edit_cash_payment'),
    url(r'^delete-cash-payment/(?P<pk>.*)/$', views.delete_cash_payment, name='delete_cash_payment'),

    url(r'create-cash-receipt/',views.create_cash_receipt, name="create_cash_receipt"),
    url(r'cash-receipts/',views.cash_receipts, name="cash_receipts"),
    url(r'^cash-receipt/(?P<pk>.*)/$', views.cash_receipt, name='cash_receipt'),
    url(r'^edit-cash-receipt/(?P<pk>.*)/$', views.edit_cash_receipt, name='edit_cash_receipt'),
    url(r'^delete-cash-receipt/(?P<pk>.*)/$', views.delete_cash_receipt, name='delete_cash_receipt'),
    

    url(r'create-journal-entry/',views.create_journal_entry, name="create_journal_entry"),
    url(r'journal-entries/',views.journal_entries, name="journal_entries"),
    url(r'^journal-entry/(?P<pk>.*)/$', views.journal_entry, name='journal_entry'),
    url(r'^edit-journal-entry/(?P<pk>.*)/$', views.edit_journal_entry, name='edit_journal_entry'),
    url(r'^delete-journal-entry/(?P<pk>.*)/$', views.delete_journal_entry, name='delete_journal_entry'),

    url(r'create-bank-payment/',views.create_bank_payment, name="create_bank_payment"),
    url(r'bank-payments/',views.bank_payments, name="bank_payments"),
    url(r'^bank-payment/(?P<pk>.*)/$', views.bank_payment, name='bank_payment'),
    url(r'^edit-bank-payment/(?P<pk>.*)/$', views.edit_bank_payment, name='edit_bank_payment'),
    url(r'^delete-bank-payment/(?P<pk>.*)/$', views.delete_bank_payment, name='delete_bank_payment'),

    url(r'create-bank-receipt/',views.create_bank_receipt, name="create_bank_receipt"),
    url(r'bank-receipts/',views.bank_receipts, name="bank_receipts"),
    url(r'^bank-receipt/(?P<pk>.*)/$', views.bank_receipt, name='bank_receipt'),
    url(r'^edit-bank-receipt/(?P<pk>.*)/$', views.edit_bank_receipt, name='edit_bank_receipt'),
    url(r'^delete-bank-receipt/(?P<pk>.*)/$', views.delete_bank_receipt, name='delete_bank_receipt'),


]

vikn-books-web/testproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve

from api.v1.users import views as users_views
from users import views as general_views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^api-auth/", include("rest_framework.urls")),
    path(
        "api/v1/auth/",
        include(
            ("api.v1.authentication.urls", "api"), namespace="api_v1_authentication"
        ),
    ),
    url(r"^app/accounts/", include("registration.backends.default.urls")),
    url("", include("pwa.urls")),
    path("api/v1/users/", include("api.v1.users.urls")),
    path("api/v1/brands/", include("api.v1.brands.urls")),
    path("api/v1/units/", include("api.v1.units.urls")),
    path("api/v1/routes/", include("api.v1.routes.urls")),
    path("api/v1/taxCategories/", include("api.v1.taxCategories.urls")),
    path("api/v1/productCategories/", include("api.v1.productCategories.urls")),
    path("api/v1/productGroups/", include("api.v1.productGroups.urls")),
    path("api/v1/warehouses/", include("api.v1.warehouses.urls")),
    path("api/v1/priceCategories/", include("api.v1.priceCategories.urls")),
    path("api/v1/accountGroups/", include("api.v1.accountGroups.urls")),
    path("api/v1/accountLedgers/", include("api.v1.accountLedgers.urls")),
    path("api/v1/branchs/", include("api.v1.branchs.urls")),
    path("api/v1/parties/", include("api.v1.parties.urls")),
    path("api/v1/products/", include("api.v1.products.urls")),
    path("api/v1/priceLists/", include("api.v1.priceLists.urls")),
    path("api/v1/masterTypes/", include("api.v1.masterTypes.urls")),
    path("api/v1/transactionTypes/", include("api.v1.transactionTypes.urls")),
    path("api/v1/colors/", include("api.v1.colors.urls")),
    path("api/v1/companySettings/", include("api.v1.companySettings.urls")),
    path("api/v1/damageStockDetails/", include("api.v1.damageStockDetails.urls")),
    path("api/v1/damageStockMaster/", include("api.v1.damageStockMaster.urls")),
    path("api/v1/designation/", include("api.v1.designation.urls")),
    path("api/v1/department/", include("api.v1.department.urls")),
    path("api/v1/employees/", include("api.v1.employees.urls")),
    path("api/v1/flavours/", include("api.v1.flavours.urls")),
    path("api/v1/journalDetails/", include("api.v1.journalDetails.urls")),
    path("api/v1/journalMaster/", include("api.v1.journalMaster.urls")),
    path("api/v1/kitchen/", include("api.v1.kitchen.urls")),
    path("api/v1/ledgerPosting/", include("api.v1.ledgerPosting.urls")),
    path("api/v1/openingStockDetails/", include("api.v1.openingStockDetails.urls")),
    path("api/v1/openingStockMaster/", include("api.v1.openingStockMaster.urls")),
    path("api/v1/paymentDetails/", include("api.v1.paymentDetails.urls")),
    path("api/v1/paymentMaster/", include("api.v1.paymentMaster.urls")),
    path("api/v1/POSHoldDetails/", include("api.v1.POSHoldDetails.urls")),
    path("api/v1/POSHoldMaster/", include("api.v1.POSHoldMaster.urls")),
    path("api/v1/purchaseDetails/", include("api.v1.purchaseDetails.urls")),
    path("api/v1/purchaseMaster/", include("api.v1.purchaseMaster.urls")),
    path("api/v1/purchaseOrderDetails/", include("api.v1.purchaseOrderDetails.urls")),
    path("api/v1/purchaseOrderMaster/", include("api.v1.purchaseOrderMaster.urls")),
    path("api/v1/purchaseReturnDetails/", include("api.v1.purchaseReturnDetails.urls")),
    path("api/v1/purchaseReturnMaster/", include("api.v1.purchaseReturnMaster.urls")),
    path("api/v1/receiptDetails/", include("api.v1.receiptDetails.urls")),
    path("api/v1/receiptMaster/", include("api.v1.receiptMaster.urls")),
    path("api/v1/salesDetails/", include("api.v1.salesDetails.urls")),
    path("api/v1/salesMaster/", include("api.v1.salesMaster.urls")),
    path("api/v1/salesOrderDetails/", include("api.v1.salesOrderDetails.urls")),
    path("api/v1/salesOrderMaster/", include("api.v1.salesOrderMaster.urls")),
    path("api/v1/salesReturnDetails/", include("api.v1.salesReturnDetails.urls")),
    path("api/v1/salesReturnMaster/", include("api.v1.salesReturnMaster.urls")),
    path("api/v1/settings/", include("api.v1.settings.urls")),
    path(
        "api/v1/stockAdjustmentDetails/", include("api.v1.stockAdjustmentDetails.urls")
    ),
    path("api/v1/stockAdjustmentMaster/", include("api.v1.stockAdjustmentMaster.urls")),
    path("api/v1/stockReceiptDetails/", include("api.v1.stockReceiptDetails.urls")),
    path("api/v1/stockReceiptMasterID/", include("api.v1.stockReceiptMasterID.urls")),
    path("api/v1/stockTransferDetails/", include("api.v1.stockTransferDetails.urls")),
    path("api/v1/stockTransferMasterID/", include("api.v1.stockTransferMasterID.urls")),
    path("api/v1/stockPostings/", include("api.v1.stockPostings.urls")),
    path("api/v1/stockRates/", include("api.v1.stockRates.urls")),
    path("api/v1/banks/", include("api.v1.banks.urls")),
    path("api/v1/financialYear/", include("api.v1.financialYear.urls")),
    path("api/v1/damageStock/", include("api.v1.damageStock.urls")),
    path("api/v1/openingStock/", include("api.v1.openingStock.urls")),
    path("api/v1/payments/", include("api.v1.payments.urls")),
    path("api/v1/posholds/", include("api.v1.posholds.urls")),
    path("api/v1/purchases/", include("api.v1.purchases.urls")),
    path("api/v1/receipts/", include("api.v1.receipts.urls")),
    path("api/v1/purchaseOrders/", include("api.v1.purchaseOrders.urls")),
    path("api/v1/purchaseReturns/", include("api.v1.purchaseReturns.urls")),
    path("api/v1/sales/", include("api.v1.sales.urls")),
    path("api/v1/salesOrders/", include("api.v1.salesOrders.urls")),
    path("api/v1/salesReturns/", include("api.v1.salesReturns.urls")),
    path("api/v1/stockAdjustments/", include("api.v1.stockAdjustments.urls")),
    path("api/v1/stockReceipts/", include("api.v1.stockReceipts.urls")),
    path("api/v1/stockTransfers/", include("api.v1.stockTransfers.urls")),
    path("api/v1/journals/", include("api.v1.journals.urls")),
    path("api/v1/countries/", include("api.v1.countries.urls")),
    path("api/v1/states/", include("api.v1.states.urls")),
    path("api/v1/businessTypes/", include("api.v1.businessTypes.urls")),
    path("api/v1/organizations/", include("api.v1.organizations.urls")),
    path("api/v1/userTable/", include("api.v1.userTable.urls")),
    path(
        "api/v1/reset-password/",
        include("django_rest_passwordreset.urls", namespace="password_reset"),
    ),
    # version2 urls
    path("api/v2/users/", include("api.v2.users.urls")),
    path("api/v2/brands/", include("api.v2.brands.urls")),
    path("api/v2/units/", include("api.v2.units.urls")),
    path("api/v2/routes/", include("api.v2.routes.urls")),
    path("api/v2/taxCategories/", include("api.v2.taxCategories.urls")),
    path("api/v2/productCategories/", include("api.v2.productCategories.urls")),
    path("api/v2/productGroups/", include("api.v2.productGroups.urls")),
    path("api/v2/warehouses/", include("api.v2.warehouses.urls")),
    path("api/v2/priceCategories/", include("api.v2.priceCategories.urls")),
    path("api/v2/accountGroups/", include("api.v2.accountGroups.urls")),
    path("api/v2/accountLedgers/", include("api.v2.accountLedgers.urls")),
    path("api/v2/branchs/", include("api.v2.branchs.urls")),
    path("api/v2/parties/", include("api.v2.parties.urls")),
    path("api/v2/products/", include("api.v2.products.urls")),
    path("api/v2/priceLists/", include("api.v2.priceLists.urls")),
    path("api/v2/masterTypes/", include("api.v2.masterTypes.urls")),
    path("api/v2/transactionTypes/", include("api.v2.transactionTypes.urls")),
    path("api/v2/colors/", include("api.v2.colors.urls")),
    path("api/v2/companySettings/", include("api.v2.companySettings.urls")),
    path("api/v2/damageStockDetails/", include("api.v2.damageStockDetails.urls")),
    path("api/v2/damageStockMaster/", include("api.v2.damageStockMaster.urls")),
    path("api/v2/designation/", include("api.v2.designation.urls")),
    path("api/v2/department/", include("api.v2.department.urls")),
    path("api/v2/employees/", include("api.v2.employees.urls")),
    path("api/v2/flavours/", include("api.v2.flavours.urls")),
    path("api/v2/journalDetails/", include("api.v2.journalDetails.urls")),
    path("api/v2/journalMaster/", include("api.v2.journalMaster.urls")),
    path("api/v2/kitchen/", include("api.v2.kitchen.urls")),
    path("api/v2/ledgerPosting/", include("api.v2.ledgerPosting.urls")),
    path("api/v2/openingStockDetails/", include("api.v2.openingStockDetails.urls")),
    path("api/v2/openingStockMaster/", include("api.v2.openingStockMaster.urls")),
    path("api/v2/paymentDetails/", include("api.v2.paymentDetails.urls")),
    path("api/v2/paymentMaster/", include("api.v2.paymentMaster.urls")),
    path("api/v2/POSHoldDetails/", include("api.v2.POSHoldDetails.urls")),
    path("api/v2/POSHoldMaster/", include("api.v2.POSHoldMaster.urls")),
    path("api/v2/purchaseDetails/", include("api.v2.purchaseDetails.urls")),
    path("api/v2/purchaseMaster/", include("api.v2.purchaseMaster.urls")),
    path("api/v2/purchaseOrderDetails/", include("api.v2.purchaseOrderDetails.urls")),
    path("api/v2/purchaseOrderMaster/", include("api.v2.purchaseOrderMaster.urls")),
    path("api/v2/purchaseReturnDetails/", include("api.v2.purchaseReturnDetails.urls")),
    path("api/v2/purchaseReturnMaster/", include("api.v2.purchaseReturnMaster.urls")),
    path("api/v2/receiptDetails/", include("api.v2.receiptDetails.urls")),
    path("api/v2/receiptMaster/", include("api.v2.receiptMaster.urls")),
    path("api/v2/salesDetails/", include("api.v2.salesDetails.urls")),
    path("api/v2/salesMaster/", include("api.v2.salesMaster.urls")),
    path("api/v2/salesOrderDetails/", include("api.v2.salesOrderDetails.urls")),

vikn-books-web/web/urls.py
from django.conf.urls import  url,include
from web import views


app_name = "web"

urlpatterns = [

    url(r'^$',views.home, name="home"),
    # url(r'create-brand/',views.create_brand, name="create_brand"),
    # url(r'brands/',views.brands, name="brands"),
    # url(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    # url(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    # url(r'account-groups/',views.account_groups, name="account_groups"),

    # url(r'create-branch/',views.create_branch, name="create_branch"),
    # url(r'branchs/',views.branchs, name="branchs"),
    # url(r'^edit-branch/(?P<pk>.*)/$', views.edit_branch, name='edit_branch'),
    # url(r'^delete-branch/(?P<pk>.*)/$', views.delete_branch, name='delete_branch'),

    # url(r'create-accountLedger/',views.create_accountLedger, name="create_accountLedger"),
    # url(r'accountLedgers/',views.accountLedgers, name="accountLedgers"),
    # url(r'^edit-accountLedger/(?P<pk>.*)/$', views.edit_accountLedger, name='edit_accountLedger'),
    # url(r'^delete-accountLedger/(?P<pk>.*)/$', views.delete_accountLedger, name='delete_accountLedger'),

    # url(r'create-bank/',views.create_bank, name="create_bank"),
    # url(r'banks/',views.banks, name="banks"),
    # url(r'^edit-bank/(?P<pk>.*)/$', views.edit_bank, name='edit_bank'),

]

vikn-books-web/accounts/models.py
from django.db import models

# Create your models here.

vikn-books-web/templates/accounts/transactions/bank_receipts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">{{title}}</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <form class="search-bar form-inline">
                                        <div class="position-relative">
                                            <input type="text" name="q" class="form-control" placeholder="Search...">
                                            <span class="mdi mdi-magnify"></span>
                                        </div>
                                    </form>                          
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-right">
                                        <a href="{% url 'accounts:create_bank_receipt' %}" class="btn btn-info waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-plus mr-1"></i>Create {{title}}</a>
                                    </div>
                                </div><!-- end col-->
                            </div>
                        
                        {% if instances %}
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-borderless table-hover mb-0">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>#</th>
                                            <th>VoucherNo</th>
                                            <th>VoucherType</th>
                                            <th>LedgerID</th>
                                            <th>EmployeeID</th>
                                            <th>ReceiptNo</th>
                                            <th>Date</th>
                                            <th>TotalAmount</th>
                                            <th>Notes</th>
                                            <th style="width: 82px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 21 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="table-user">
                                                <a href="javascript:void(0);" class="text-body font-weight-semibold">{{ instance.id }}</a>
                                            </td>
                                            
                                            <td>
                                                {{ instance.VoucherNo }}
                                            </td>
                                            <td>
                                                {{ instance.VoucherType }}
                                            </td>
                                            <td>
                                                {{ instance.LedgerID }}
                                            </td>
                                            <td>
                                                {{ instance.EmployeeID }}
                                            </td>
                                            <td>
                                                {{ instance.ReceiptNo }}
                                            </td>
                                            <td>
                                                {{ instance.Date }}
                                            </td>
                                            <td>
                                                {{ instance.TotalAmount }}
                                            </td>
                                            <td>
                                                {{ instance.Notes }}
                                            </td>
                                            <td>
                                                <a href="{% url 'accounts:bank_receipt' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                                <a href="{% url 'accounts:edit_bank_receipt' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                                <a data-id="{{instance.pk}}" href="{% url 'accounts:delete_bank_receipt' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-icon action-button remove"> <i class="mdi mdi-delete"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <!--pagination -->
                            {% get_pages %}
                             <div class="pagination pagination-rounded justify-content-end my-2">
                                {% show_pages %}
                            </div>
                            <!--pagination-->
                            {% else %}
                            {% include 'includes/not_found.html' %}
                            {% endif %}

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}

vikn-books-web/templates/accounts/transactions/cash_payments.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
            
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                <li class="breadcrumb-item active">{{title}}</li>
                            </ol>
                        </div>
                        <h4 class="page-title">{{title}}</h4>
                    </div>
                </div>
            </div>     
            <!-- end page title --> 

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6">
                                    <form class="search-bar form-inline">
                                        <div class="position-relative">
                                            <input type="text" name="q" class="form-control" placeholder="Search...">
                                            <span class="mdi mdi-magnify"></span>
                                        </div>
                                    </form>                          
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-right">
                                        <a href="{% url 'accounts:create_cash_payment' %}" class="btn btn-info waves-effect waves-light mb-2 mr-2"><i class="mdi mdi-plus mr-1"></i>Create {{title}}</a>
                                    </div>
                                </div><!-- end col-->
                            </div>
                        
                        {% if instances %}
                            <div class="table-responsive">
                                <table class="table table-centered table-nowrap table-borderless table-hover mb-0">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>#</th>
                                            <th>VoucherNo</th>
                                            <th>VoucherType</th>
                                            <th>LedgerID</th>
                                            <th>EmployeeID</th>
                                            <th>PaymentNo</th>
                                            <th>Date</th>
                                            <th>TotalAmount</th>
                                            <th>Notes</th>
                                            <th style="width: 82px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 21 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="table-user">
                                                <a href="javascript:void(0);" class="text-body font-weight-semibold">{{ instance.id }}</a>
                                            </td>
                                            
                                            <td>
                                                {{ instance.VoucherNo }}
                                            </td>
                                            <td>
                                                {{ instance.VoucherType }}
                                            </td>
                                            <td>
                                                {{ instance.LedgerID }}
                                            </td>
                                            <td>
                                                {{ instance.EmployeeID }}
                                            </td>
                                            <td>
                                                {{ instance.PaymentNo }}
                                            </td>
                                            <td>
                                                {{ instance.Date }}
                                            </td>
                                            <td>
                                                {{ instance.TotalAmount }}
                                            </td>
                                            <td>
                                                {{ instance.Notes }}
                                            </td>
                                            <td>
                                                <a href="{% url 'accounts:cash_payment' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                                <a href="{% url 'accounts:edit_cash_payment' pk=instance.pk %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                                <a data-id="{{instance.pk}}" href="{% url 'accounts:delete_cash_payment' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-icon action-button remove"> <i class="mdi mdi-delete"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <!--pagination -->
                            {% get_pages %}
                             <div class="pagination pagination-rounded justify-content-end my-2">
                                {% show_pages %}
                            </div>
                            <!--pagination-->
                            {% else %}
                            {% include 'includes/not_found.html' %}
                            {% endif %}

                        </div> <!-- end card-body-->
                    </div> <!-- end card-->
                </div> <!-- end col -->
            </div>
            <!-- end row -->
            
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}